# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  release:
    permissions:
      contents: write # To upload release assets.
      actions: read   # To read workflow path.

    runs-on: ubuntu-latest

    steps:

      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          # Fetch whole repository to get release tags
          # See https://github.com/actions/checkout/issues/701
          fetch-depth: 0

      -
        name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        #env:
        #  # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        #  # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
