# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build validation and Unit Testing

on: [pull_request, workflow_dispatch]

jobs:
  validate:
    name: Testing build

    strategy:
      matrix:
        os: ['ubuntu-latest']
        
        go-version: [1.18.x]
        go-arch: [ amd64 ]
        go-os: [ linux ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build
        run: go build -o build/${{ github.event.repository.name }}-${{ matrix.go-os }}-${{ matrix.go-arch }} -v
        env:
          GOARCH: ${{ matrix.go-arch }}
          GOOS: ${{ matrix.go-os }}
        
      - name: Test
        run: go test -v -cover -race -timeout 120s ./...
